# Generated by Django 3.0.3 on 2020-04-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_auto_20200404_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='cel',
            field=models.IntegerField(blank=True, verbose_name='Telefono'),
        ),
    ]
