# Generated by Django 3.0.3 on 2020-04-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_auto_20200407_0230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleados',
            options={'ordering': ['name'], 'verbose_name': 'Conductor', 'verbose_name_plural': 'Conductores'},
        ),
        migrations.AlterField(
            model_name='empleados',
            name='cel',
            field=models.IntegerField(verbose_name='Telefono'),
        ),
        migrations.AlterUniqueTogether(
            name='empleados',
            unique_together={('name', 'last_name')},
        ),
    ]
