# Generated by Django 3.0.3 on 2020-06-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_auto_20200410_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='cel',
            field=models.CharField(max_length=11, verbose_name='Telefono'),
        ),
    ]
