# Generated by Django 3.0.3 on 2020-06-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_auto_20200603_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='cel',
            field=models.CharField(max_length=10, verbose_name='Telefono'),
        ),
    ]
