# Generated by Django 3.0.3 on 2020-04-07 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0004_auto_20200407_0230'),
        ('camiones', '0001_initial'),
        ('rutas', '0010_auto_20200407_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contador', models.CharField(max_length=50, verbose_name='contador')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleados')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutas.rutas')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camiones.camiones')),
            ],
        ),
    ]
