# Generated by Django 3.0.3 on 2020-04-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_auto_20200407_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutas',
            name='ruta',
            field=models.CharField(choices=[('2', 'Ruta 8'), ('0', 'Ruta 6'), ('3', 'Ruta 1'), ('1', 'Ruta 10')], max_length=1, verbose_name='Ruta'),
        ),
    ]
