# Generated by Django 3.0.3 on 2020-04-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0003_auto_20200407_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutas',
            name='ruta',
            field=models.CharField(choices=[('0', 'Ruta 6'), ('3', 'Ruta 1'), ('1', 'Ruta 10'), ('2', 'Ruta 8')], max_length=1, verbose_name='Ruta'),
        ),
    ]
