# Generated by Django 3.0.3 on 2020-04-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0008_auto_20200407_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutas',
            name='ruta',
            field=models.CharField(choices=[('1', 'Ruta 10'), ('3', 'Ruta 1'), ('2', 'Ruta 8'), ('0', 'Ruta 6')], max_length=1, verbose_name='Ruta'),
        ),
    ]
