# Generated by Django 3.0.3 on 2020-06-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0012_auto_20200410_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutas',
            name='ruta',
            field=models.CharField(choices=[('0', 'Ruta 6'), ('1', 'Ruta 10'), ('3', 'Ruta 1'), ('2', 'Ruta 8')], max_length=1, verbose_name='Ruta'),
        ),
    ]
