# Generated by Django 3.0.3 on 2020-06-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0013_auto_20200603_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutas',
            name='ruta',
            field=models.CharField(choices=[('1', 'Ruta 10'), ('3', 'Ruta 1'), ('2', 'Ruta 8'), ('0', 'Ruta 6')], max_length=1, verbose_name='Ruta'),
        ),
    ]
