# Generated by Django 3.0.3 on 2020-04-10 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camiones',
            options={'ordering': ['unidad'], 'verbose_name': 'Unidades', 'verbose_name_plural': 'Camiones'},
        ),
    ]
